src/locales/en/translation.json

Text change

---

src/shared/components/DetailsPanel/components/SharePanel/index.js
src/shared/components/DetailsPanel/components/SharePanel/styles.js
src/shared/components/ThirdPartyAuth/index.js
src/views/Auth/SignIn/index.js
src/views/Auth/SignUp/index.js

- Trigger share modal when clicking on manage:

Show splash for torus flows

---

src/shared/components/Layout/components/Account/index.js

Clicking help on the menu triggers an email.

clicking help triggers email

---

src/shared/components/PrivateRoute/index.js
src/shared/components/UsernamePasswordForm/index.js
src/views/Auth/SignIn/index.js
src/views/Auth/SignUp/index.js

Signup as default auth view and keep username/password

---

public/electron/events/add-items-subscribe.js

- Fix duplicated files after upload on windows

Fix duplicated files after upload on windows

---

src/shared/components/Modal/FileLinkPassword/index.js

Revert fName change

---

src/events/account.js
src/reducers/user.js
src/shared/components/Modal/Prompt/Prompt.js
src/shared/components/Modal/Prompt/styles.js
src/shared/components/Modal/Settings/views/Account/Account.js
src/shared/components/Modal/Settings/views/Account/get-handlers.js
src/shared/components/Notifications/utils/map-data-to-items.js

Loading/error state for user update and Notification icon fix

---

src/shared/components/Notifications/utils/map-data-to-items.js

Order notification by timestamp field

---

src/shared/components/ObjectsTable/ObjectsTable.js
src/shared/components/ObjectsTable/styles.js
src/views/Storage/shared/getTableHeads.js

added sorting feature

---

public/electron/events/notifications.js
src/App.js
src/UI/Notification/NotificationItem/NotificationItem.js
src/events/index.js
src/events/notifications.js
src/reducers/notifications.js
src/shared/components/Notifications/Notifications.js

- Redirect to shared-by route after accept shared file
- Handle loading state before redirect

Redirect to shared-by route after accept shared file

---

src/shared/components/ObjectsTable/ObjectsTable.js
src/views/Storage/DetailsPanel/index.js
src/views/Storage/SharedBy/index.js
src/views/Storage/shared/RenderRow.js
src/views/Storage/shared/components/FileTable/index.js

- Fix sub-files selection
- Fix double click navigation on expanded sub folders
- Fix extra offset for shared files

Fix sub-files selection

---

src/views/Storage/shared/components/FileTable/index.js

- Fix navigation inside sub-folders

Fix navigation inside sub-folders

---

src/shared/components/DetailsPanel/DetailsPanel.js
src/shared/components/Layout/components/Sidebar/styles.js
src/views/Storage/DetailsPanel/index.js
src/views/Storage/DetailsPanel/styles.js

fix layout border style

---

src/shared/components/Dropzone/index.js
src/shared/components/Dropzone/styles.js
src/shared/components/ObjectsTable/ObjectsTable.js
src/utils/get-tabulations.js
src/utils/index.js
src/views/Storage/shared/RenderRow/index.js

fix dropzone

---

package.json
yarn.lock

- Updated space client ver 1.1.9

Updated space client ver 1.1.9

---

src/UI/Table/components/LoadingCell/loading-cell.stories.js
src/UI/Table/components/MemberCell/MemberCell.js
src/UI/Table/components/MemberCell/index.js
src/UI/Table/components/MemberCell/member-cell.stories.js
src/UI/Table/components/MemberCell/styles.js
src/UI/Table/components/index.js
src/UI/Table/table.stories.js
src/locales/en/translation.json
src/views/Storage/SharedBy/index.js
src/views/Storage/shared/RenderRow/index.js
src/views/Storage/shared/ShareRenderRow/SharedRenderRow.js
src/views/Storage/shared/ShareRenderRow/index.js
src/views/Storage/shared/ShareRenderRow/styles.js
src/views/Storage/shared/components/FileTable/index.js
src/views/Storage/shared/getTableHeads.js
src/views/Storage/shared/helpers/get-row-offset.js

Added shared row

---

src/views/Storage/shared/RenderRow/index.js

- removed loading icon for folders

remove loading icon for folders

---

src/UI/Notification/NotificationItem/NotificationItem.js
src/UI/Notification/NotificationItem/styles.js
src/UI/Table/table.stories.js
src/shared/components/ObjectsTable/utils/hover-menu-on-click.js

Fix notifications styles

---

src/config.js
src/locales/en/translation.json
src/shared/components/ThirdPartyAuth/index.js
src/utils/index.js
src/utils/use-auth0-passwordless.js
src/utils/use-torus-sdk.js
src/views/Auth/EmailLinkAuth/EmailLinkAuth.js
src/views/Auth/SignIn/index.js
src/views/Auth/SignUp/index.js

Passwordless sign in/up integration

---

package.json
public/electron/events/objects.js
src/utils/object-presenter.js
src/views/Storage/shared/ShareRenderRow/SharedRenderRow.js
yarn.lock

- Added support for sharedBy Field

Added support for sharedBy Field

---

src/utils/use-double-click.js

- default useDoubleClick to singleClick

default useDoubleClick to singleClick

---

public/electron/events/add-items-subscribe.js
src/events/add-items-subscribe.js
src/reducers/storage/index.js
src/shared/components/DetailsPanel/components/Header/index.js
src/shared/components/Layout/components/CreateNewButton/index.js
src/shared/components/Modal/UploadProgress/index.js
src/shared/components/ObjectsTable/ObjectsTable.js
src/shared/components/ObjectsTable/utils/get-context-menu.js
src/shared/components/ObjectsTable/utils/hover-menu-on-click.js
src/utils/create-error-objects.js
src/utils/index.js
src/views/Storage/shared/RenderRow/index.js

1. Make error row appear when there's an error while uploading an item.
2. Disable functionality that won't work with unuploaded file such as sharing, opening.
3. Added ability to "cancel" by removing item from the table

Ch20641/upload error + cancel button
